### ISSUE TITLE
Bluetooth Mouse and Keyboard for PSTV

### ISSUE THREAD

**Issue by Invictaz** [Northfear/Vanilla-Conquer-vita#1]
Several PSVita homebrew titles have the option to add a bluetooth mouse and keyboard combo.
AFAIK Julius has this.

That would allow much better control of this game on PSTV.

**Comment by Northfear** [comment]
It's not working right now? I don't think that I've added any functionality that would break KB+M

**Comment by Northfear** [comment]
I'm closing this one. Fell free to reopen it if K+M aren't working indeed (it was neither confirmed nor denied). I don't have anything bluetooth to test it right now.
