### ISSUE TITLE
C&C - Red Alert is crashing during mission

### ISSUE THREAD

**Issue by J013k** [Northfear/Vanilla-Conquer-vita#2]
Hi.
I have a problem with randomly crashes in some missions.

Let say that everything is fine when I have a "poor" base...
I mean not many buildings, troops, etc.

Once my base is getting bigger,
at some point when I want to attack the opponent game is crashing.

Here are my dumps from these crashes:
https://www.mediafire.com/file/78m4n8k0aa5m6lj/C%2526C-RA_Log.7z.

I hope that these dumps might help in some way...

Best regards.

**Comment by Northfear** [comment]
Any specific mission? Or is it happening everywhere? Savegames maybe?
Also old savegames might not work after the game update (some _might_ work, but generally it's a good idea to restart a map after an update).

**Comment by Northfear** [comment]
Also here's the test build. Let me know if it helps with your crashes
[vanilla-conquer.zip](https://github.com/Northfear/Vanilla-Conquer-vita/files/6349490/vanilla-conquer.zip)

**Comment by J013k** [comment]
I am not sure how can I report this bug because it happens randomly and after a longer period of time*...

E.g. I have a save game when I wanted to destroy Soviet's radar, 
the game for a short period of time slows down significantly and after a while it crashes.
When I quit the game reload the save game, crash happens one more time.
After **rebooting** the console, loading game everything was fine...

In next message I will try to upload a save and post my results from a new test build that you uploaded.

Thanks.


[*] - of course I still have to have many buildings, troops, etc.

**Comment by J013k** [comment]
Because this issue happens randomly I'm not able to create a proper save before crash...

Theoretically everything is fine after resetting the console.

Anyway...
One other thing that I notice in a new test build is that after some time the left analog will begins to "fail".
In this video it is constantly resetting position:
https://www.mediafire.com/file/fmjdilzcf1o5b43/VID_20210421_195459.3gp.7z.

I have also noticed that sometimes the left analog is acting like the right one.
I mean no matter which analog I'll push they both are "acting" as the right one,
so I can only scroll the map or I have to use the front touch panel (display) to select anything, etc.

These issues mostly happens after a longer period of time, so currently I can "catch" them on a camera...
because it is pointless (or I am not exactly sure how to do it) with my knowledge to debug these issues properly
or to create extended bug report...

**Comment by Northfear** [comment]
3 finger tap on rear touchpad switches left analog between cursor movement and map scroll

**Comment by J013k** [comment]
![https://how2play.pl/wp-content/uploads/2015/11/172636.gif](https://how2play.pl/wp-content/uploads/2015/11/172636.gif)

...

Sorry for that.

I will at least somehow try to test this port more "detailedly"...

Thanks & best regards.

**Comment by Northfear** [comment]
That's ok. I've added it somewhere between updates, so it's not a surprise that people missed it (it's not that easy to trigger it by accident on my Vita tho. That's probably happening due to bigger rear touchpad on 1000 model)
Any updates on crashes? Are they still happening? Does it takes longer for them to show up if "yes"?

**Comment by J013k** [comment]
Let's do this a little bit differently...
Since no one else is "_complaining_", recently I have a very limited time for tests, so I cannot give a proper report...

Let's close this issue, once I will have more time for tests I will at least try to make a few screenshots and
additionally a crash log report if I find any problem.

Best regards.

**Comment by Northfear** [comment]
@J013k there's a known issue with Repair facility in tiberium dawn that crashes the game, but most of the crashes from your dumps were due to memory allocation. I suspect that there's either too little memory or some kind of a mem leak involved. Test builds increased available memory by 130 mb or so. So that should've at least delayed the crash.
