### ISSUE TITLE
Moving the cursor using the rear touchpad 

### ISSUE THREAD

**Issue by Gmaarcik** [Northfear/Vanilla-Conquer-vita#3]
is this an issue or a request, i don't know yet.
Is there a way to enable the rear touchpad like a mousepad 
or the three fingers gesture preventing it to be used ?
I've had the same question about Open X-COM.

**Comment by Northfear** [comment]
It should be possible, yeah, but I'm pretty sure that accidental rear touchpad hits would just mess up controls badly

**Comment by Gmaarcik** [comment]
How about a switch to swap rear/front touch  ?
(to me) using rearpad feels more comfortable/natural using a grip, 

this would allow to keep the front for simple switch like gesture and rearpad for the cursor.

**Comment by Northfear** [comment]
@garcimak what are some good examples of HB apps that are using rear touchpad for cursor conrols? And could you describe how to use it properly at least? (ergonomically. and how to handle clicks, etc). Julius has front touch "trackpad" mode (which I actually had in fheroes2 before). ScummVM has some kind or rear trackpad support, but it seems a bit messed up in version 2.2.0

**Comment by Gmaarcik** [comment]
@Northfear   for example  : rsn8887's Enigma, front and rear touch controls
in uae4all2 you can have both (front/rear both)

official adventure games like machinarium, demetrios 
also use this scheme

scummvm works out of the box for me,  just checked i'm still in 2.1.0 so will try to update to see what they messed up, playing it alot but it was perfect.   
Edit :  2.1.1 et 2.2.0 are fine too with me, rearpad speed option set to 13 

i tried julius and the rearpad isn't working, i swear i've seen it handled by rearpad in a yt video, maybe it was some sort of plugin (if it's works fine i'd have to dig this as a workaround)

controls : 
it depends of types of games but usually 
used for indirect mouse input, like on a laptop touchpad. Move a single finger to move the mouse pointer. Use short tap for left click. Hold a single finger while tapping a second finger for right click. Drag with two fingers to drag and drop.

ergonomicaly : 
 in action with both model, my middle finger are within range of the rearpad area
![vita grips](https://user-images.githubusercontent.com/48183989/129353538-cbd79d59-8cfe-4374-8135-d233291d4b7f.jpg)
![vita handling-600](https://user-images.githubusercontent.com/48183989/129353567-f1cf6ea5-63b5-4448-9084-20f4ddcd3613.jpg)

**Comment by Northfear** [comment]
@garcimak here's the build with cursor movement. LMB emulation on tap with <0.5 seconds release delay. Can make it movement only if it feels uncomfortable.
[vanilla_rear.zip](https://github.com/Northfear/Vanilla-Conquer-vita/files/7574627/vanilla_rear.zip)

You can edit movement speed with `RearTouchSpeed` option in config files.

**Comment by Gmaarcik** [comment]
Noice!    cursor handles pretty fine with "RearTouchSpeed=8" 
now how much is the highest value ?
as it is, any micro movement <0.5 triggers LMB 
making accidental airtrikes and such occurs 
so before trying movement only :
personally i prefer keeping the LMB by tap (lowest value ?)
an maybe reserve some other binding to physical buttons like left analog wich could be reuse for more mapping but this is another story.
 
by the way i know a little about controlling things like teambuilding, using 1-4 dpad keys but what about assigning guard mode and exceptional escort ?
triangle is scatter but for the rest i'm a confused about how key bindings work.
Thanks Northfear !

**Comment by Northfear** [comment]
No highest value really.
So you want to try even smaller delay, right?
As for bindings, guard is already assigned to square I think. And escort has no binding.

**Comment by Gmaarcik** [comment]
> No highest value really. So you want to try even smaller delay, right? 

yeah, i like how it works in Enigma's menu for instance. are they sharing same libs ?

**Comment by Northfear** [comment]
@garcimak 
Reduced delay by the half
[vanilla_rear.zip](https://github.com/Northfear/Vanilla-Conquer-vita/files/7613381/vanilla_rear.zip)

**Comment by Gmaarcik** [comment]
Cheers ! mouse control meets expectations :-)

btw If it's a issue,  by trying the command bindings i noticed an inconsistancy in the port
 
in your info : Use R1 + D-Pad to create teams (1-4) and D-Pad to select them (same as Ctrl + 1-4 on keyboard). You can use DPad numbers while entering savegame names.

but actually L1 is binded to 'ctrl' instead R1.

indeed it's bit awkward to use index maintening the L1 key pressed and activate 1-4 with the same hand's thumb.

also i've the feeling that pressing 'alt' actually does nothing, 
in og red alert, When the player presses the Alt key the crossair becomes green and with right click the unit moves to the given location (force move)

But the crosshair doesn't change here , dunno if it is port related. 

i think the alt key is only needed to escort with the 'alt'+'ctrl'+'Left' CLICK combo and force move.
 Let me know if i was correct thinking R1 must be ctrl and L1 for 'alt'.

**Comment by Northfear** [comment]
> btw If it's a issue, by trying the command bindings i noticed an inconsistancy in the port

It's a typo. It was always L1

> also i've the feeling that pressing 'alt' actually does nothing,

It's still a force move like before (it's staying green even if you're hovering it over enemy unit)

Btw I was thinking about another way of doing LMB emulation with touchpad. What about "short double tap". First tap doesn't emulate anything, while second (if it hits within a short time) emulates both "down" (so you could select units for example) and "up" click.

**Comment by Gmaarcik** [comment]
LMB one tap as direct order is already functionnal to my liking but i'm willing to test out what you will come with.  About L&R triggers, up to you if it's not a hassle inverting the 'alt' 'ctrl' keys, i think that would be neat to try too.

let's hope you have the time and energy to include the mouse control in your other production HOMM2 comes in mind first, excited to mess around with.

**Comment by Northfear** [comment]
I guess I can close this one, since rear touchpad support was added a while ago. But if you shill have any suggestions you can leave them here.
