### ISSUE TITLE
two bugs and a control change suggestion

### ISSUE THREAD

**Issue by srs008** [Northfear/Vanilla-Conquer-vita#4]
I'm not even sure this is getting checked...

I've got a simple suggestion, and some bugs. obviously the bugs are first.

----
system

sd2vita (64gb)
3.60 (two Japanese symbols) -10
---

since i can't nail the bugs directly, I'll have to mention what i think is going on.
basically, if the music and sound is enabled, the first bug you'll notice is frequent music track resets. as in, it'll never finish the song
before something triggers a reset of it.
if i had to guess, it seems to be voices, e.g most of the time i feel like EVA speaks about that time.

now i tend to play skirmish with max ai, honestly it's the only part i've not played to death yet.
but it feels like the game runs out of memory after a while, just by the erratic way it force closes after a long play period.

today, i did some things different, the first thing i did was turned off sound effects entirely, so it was just music, it did once reset. just once.
the second thing was i only played with two ai (it gave me a gdi and a nod, so it's probably not a side related issue at least)

maybe these can help you track down this bug
=====================

as for the suggestion, can we have the "left shoulder" added to the "three finger" tap on the rear touchpad?
barring the crashing, the game runs well, but that touchpad often gets nudged...
since the left shoulder is force attack, adding it to this combo should not effect the gameplay, but should stop the 
touchpad being randomly triggered nearly as much.

**Comment by Northfear** [comment]
Hey
Could you check this build please?
https://github.com/Northfear/Vanilla-Conquer-vita/files/6349490/vanilla-conquer.zip
It should have more RAM available. Looks like there's a memleak somewhere, but more RAM should at least delay the crash.
And I totally support that touch idea. Was thinking about switching it to something like R+L+START, because 1000 models seem to have a lot of troubles with it due to bigger rear touchpad.

**Comment by Northfear** [comment]
@srs008 here's pre-release with increased memory allocation and different key combo for switching between modes
https://github.com/Northfear/Vanilla-Conquer-vita/releases/tag/v0-vita.4
Let me know how it goes. I'll make it official if it at least somewhat delays the crash

**Comment by srs008** [comment]
well it plays much better, this time i think i got the crashdump, so that's a start. 
[psp2core-1624770355-0x00000e2fe5-eboot.bin.zip](https://github.com/Northfear/Vanilla-Conquer-vita/files/6721066/psp2core-1624770355-0x00000e2fe5-eboot.bin.zip)

since i don't know what's causing the crash. ingame i'd just blocked my base off for a breather (ran out of tiberium, so it could be a pathing crash here)

and yep, it's a 1000 series, i've not tried ra at all honestly, so i'll have to see if i can replicate it there as well.

thanks for your quick response, and time

**Comment by Northfear** [comment]
Was it with v0-vita.4 pre-release or the file above it?

**Comment by Northfear** [comment]
I suspect that this was related to unit repair bug. I've fixed that one today and released v0-vita.4. This should improve CnC situation on Vita.

**Comment by srs008** [comment]
i should have mentioned, it was the release you suggested, (https://github.com/Northfear/Vanilla-Conquer-vita/releases/tag/v0-vita.4)

**Comment by Northfear** [comment]
@srs008 great. Then re-download final build of v0-vita.4 and give it a go. Repair bug is fixed now (other way around it was using speech.mix from covert ops)

**Comment by srs008** [comment]
i'll be running it soon, going to cook today's meal soon, good chance to stretch out.

**Comment by srs008** [comment]
okay, easily my longest session, been running from about 20 minutes after the last message. either it was a hell of a fluke run, or you've got the bug proper.

as for the sound annoyance (music change), a fairly surefire way of replicating it is to play music, and destroy some buildings. seems to trigger more often then anything else i've seen.
either way, the game is now VERY playable. so main goal achieved by the looks.

**Comment by Northfear** [comment]
Glad to hear that!
As for the other bugs, I'd recommend creating an issue for Vanilla Conquer team directly
https://github.com/TheAssemblyArmada/Vanilla-Conquer
I'm mostly just maintaining Vita port here, so my knowledge of CnC engine is pretty limited.
