### ISSUE TITLE
(possible bug?) aircraft can attack eachother midair

### ISSUE THREAD

**Issue by srs008** [Northfear/Vanilla-Conquer-vita#5]
figured i'd better make this a separate bug report, although it's more a feature.

i'm under the impression the vanilla conquer project is a true port, as in, they are not trying to add features, but ensure it works as close to perfect as possible.

so, ra2 is more my thing, and even then, i'm not that great. just overly familiar. 
that said, i played the older games enough, and modded ra2+yr (vanilla) enough to learn a few of the workings, the aircraft thing was a targeting bug if memory serves. basically, it produced a hard crash with air to air.
some hacks were implemented, e.g i vaguely remember someone dropping a "bomb" that launched a projectile from the ground.
but that meant it had ground targeting, and was weird.

but until they started editing the game engine, i remember the mod community had no solution.

it played and behaved fine, but i'm thinking it might be a indication of a tagging error, 
(e.g from ra2's patriot missile projectile data) (the values might be different, i tend to tweak defence in my "mods")
---------------------
[AAHeatSeeker]
Arm=2
Shadow=no
Proximity=yes
Ranged=yes
AA=yes
AG=no
;AN=no
Image=DRAGON
ROT=80 ;10
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
----------------------------

since i'm not familiar with gen 1, i can't give a definite answer on things, so i apologize for that. it's mostly raw gameplay i have to compare with, but if the tags are not working, then it might be making the ai consider weird things it should be ignoring.
this then turns into a pile of actions "can i do it?".
and that just expands. suddenly, surprise, Out of memory.
programming may not be my thing, but computer logic is just dumb. the tinest thing can interact, or not, and snowball, and six hours down the line, explode.
(i think dolphin emu covered this "recently" with a final fantasy game logic glitch actually).
so yeah, i notice something that seems off, i'll mention it. it's probably a feature working correctly, but if not, this could be a good pointer at least.

**Comment by Northfear** [comment]
I'm closing this one, since it looks more like an upstream stuff..
